// src/topics/16-global-state/vue/StoreApiDemo.vue
<script setup lang="ts">
/**
 * 区块二 Vue 对照：Pinia store 的实例 API —— storeToRefs 的坑、$patch、自写 $reset、$subscribe、$onAction、
 * 组件外使用、异步 action、持久化插件。对照 react/StoreApiDemo.tsx（getState / setState / subscribe / persist）。
 */
import { computed, ref } from 'vue'
import { storeToRefs } from 'pinia'
import { CART_STORAGE_KEY, getCheckoutRequestCount, useCartStore } from './cartStore'
import { DEMO_PRODUCTS } from './products'

const { delayMs = 600 } = defineProps<{ delayMs?: number }>()

const cart = useCartStore()
const { totalCount, checkout } = storeToRefs(cart)
// ❌ 直接解构 getter / state：拿到的是这一刻的值（普通数字），之后购物车再变，它也不会变
const { totalCount: frozenCount } = cart

const log = ref<string[]>([])
const push = (line: string) => {
  log.value = [...log.value, line].slice(-12)
}

/**
 * $subscribe：state 变化后回调。直接改 state 的变化按 watch 的默认时机（flush: 'pre'）在同一个 tick 里合并成一次，
 * type 是 'direct'；$patch 会暂停这个 watcher、立刻同步回调一次，type 是 'patch object' / 'patch function'。
 * 在组件里调用时随组件卸载自动取消；要保留就传 { detached: true }。
 */
cart.$subscribe((mutation) => {
  push(`$subscribe：${mutation.type}`)
})

/**
 * $onAction：每个 action 调用之前触发；after 在 action 完成后调用（async action 会等 Promise 完成），
 * onError 在 action 抛错或 Promise 被拒绝时调用。注意它的 detached 是第二个参数（$onAction(cb, true)），
 * 和 $subscribe 的 { detached: true } 写法不一样。
 */
cart.$onAction(({ name, after, onError }) => {
  push(`$onAction：${name} 开始`)
  after(() => push(`$onAction：${name} 完成${name === 'checkoutCart' ? `（服务端累计 ${getCheckoutRequestCount()} 次结算请求）` : ''}`))
  onError((err) => push(`$onAction：${name} 出错：${String(err)}`))
})

/** 组件外（普通函数）使用 store：在 app.use(pinia) 之后调用即可；服务端渲染时要把当前请求的 pinia 传进去 useCartStore(pinia) */
function logoutAndClearCart() {
  useCartStore().clear()
}

const failNext = ref(false)
const storageText = ref('')
const statusText = computed(() =>
  checkout.value.status === 'success'
    ? `结算状态：success，订单号 ${checkout.value.orderNo}`
    : `结算状态：${checkout.value.status}`,
)

function patchObject() {
  // 对象形式：普通对象会深合并，数组整体替换
  cart.$patch({ giftWrap: !cart.giftWrap })
}

function patchFunction() {
  // 函数形式：适合 push 数组、一次改多个字段；函数必须是同步的
  cart.$patch((state) => {
    state.items.push({ id: 'p4', name: DEMO_PRODUCTS[3].name, price: DEMO_PRODUCTS[3].price, quantity: 1 })
    state.giftWrap = true
  })
}

function checkoutTwice() {
  // 同一轮里连调两次：第二次读到 checkout.status === 'pending' 直接返回
  void cart.checkoutCart({ delayMs, fail: failNext.value })
  void cart.checkoutCart({ delayMs, fail: failNext.value })
}

function readStorage() {
  storageText.value = localStorage.getItem(CART_STORAGE_KEY) ?? '（localStorage 里没有这个键）'
}
</script>

<template>
  <div class="card stack">
    <h3>区块二：store 实例 API、组件外使用、异步 action、持久化插件</h3>

    <strong>1. storeToRefs 与直接解构</strong>
    <p>
      storeToRefs：<strong>{{ totalCount }}</strong> 件 · 直接解构（不会更新）：<strong>{{ frozenCount }}</strong> 件
    </p>

    <strong>2. $patch 与自写的 $reset</strong>
    <div class="row">
      <button @click="patchObject">
        $patch 对象形式：切换礼品包装
      </button>
      <button @click="patchFunction">
        $patch 函数形式：加一台显示器 + 礼品包装
      </button>
      <button @click="cart.$reset()">
        $reset()（setup store 自己写的）
      </button>
      <button @click="logoutAndClearCart">
        模拟「退出登录」：组件外清空购物车
      </button>
    </div>

    <strong>3. 异步 action：结算</strong>
    <div class="row">
      <button
        class="btn-primary"
        :disabled="checkout.status === 'pending'"
        @click="cart.checkoutCart({ delayMs, fail: failNext })"
      >
        {{ checkout.status === 'pending' ? '结算中…' : '结算' }}
      </button>
      <button
        :disabled="checkout.status === 'pending'"
        @click="checkoutTwice"
      >
        同一轮里调用两次 checkoutCart()
      </button>
      <label class="row">
        <input
          v-model="failNext"
          type="checkbox"
        >
        模拟结算失败
      </label>
    </div>
    <p role="status">
      {{ statusText }}
    </p>
    <p
      v-if="checkout.status === 'error'"
      role="alert"
      class="error-text"
    >
      {{ checkout.message }}（购物车保留，可以重试）
    </p>

    <strong>4. 持久化插件（persistPlugin.ts）</strong>
    <div class="row">
      <button @click="readStorage">
        查看 localStorage
      </button>
    </div>
    <pre
      v-if="storageText"
      class="log"
      aria-label="localStorage 内容"
    >{{ storageText }}</pre>

    <strong>5. $subscribe / $onAction 日志</strong>
    <pre
      class="log"
      aria-label="store 日志"
    >{{ log.length === 0 ? '（还没有变化）' : log.join('\n') }}</pre>
  </div>
</template>

// src/topics/16-global-state/react/StoreApiDemo.tsx
/**
 * 区块二【主线】：在组件外读写 store、subscribe、异步 action、persist。
 * useCartStore 既是 Hook，也是一个挂着 getState / setState / subscribe / getInitialState 的对象（zustand esm/react.mjs:17）。
 * Vue 对照：vue/StoreApiDemo.vue（$subscribe / $onAction / $patch / 自写 $reset）。
 */
import { useEffect, useState, useSyncExternalStore } from 'react'
import { CART_STORAGE_KEY, getCheckoutRequestCount, selectTotalCount, useCartStore, type CartState } from './cartStore'

/* ------------------ 演示日志：组件外的小 store（和 14 / 19 题同一个做法） ------------------ */

function createDemoLog() {
  let lines: readonly string[] = []
  const listeners = new Set<() => void>()
  return {
    push(line: string) {
      lines = [...lines, line].slice(-12)
      listeners.forEach((listener) => listener())
    },
    subscribe(listener: () => void) {
      listeners.add(listener)
      return () => {
        listeners.delete(listener)
      }
    },
    getSnapshot: () => lines,
  }
}

type DemoLog = ReturnType<typeof createDemoLog>

/** 把一次 store 变化翻译成人能读的日志（只比较关心的字段） */
function describeChange(state: CartState, prev: CartState): string[] {
  const out: string[] = []
  if (state.items !== prev.items) out.push(`items：${selectTotalCount(prev)} 件 → ${selectTotalCount(state)} 件`)
  if (state.giftWrap !== prev.giftWrap) out.push(`giftWrap：${prev.giftWrap} → ${state.giftWrap}`)
  if (state.checkout !== prev.checkout) {
    const detail =
      state.checkout.status === 'success'
        ? `（${state.checkout.orderNo}；服务端累计收到 ${getCheckoutRequestCount()} 次结算请求）`
        : state.checkout.status === 'error'
          ? `（${state.checkout.message}）`
          : ''
    out.push(`checkout：${prev.checkout.status} → ${state.checkout.status}${detail}`)
  }
  return out
}

/**
 * 「退出登录」这类非 React 代码（请求拦截器、WebSocket 回调、路由守卫）要改 store 时：
 * 用 getState() 拿到 action 再调用。也可以 useCartStore.setState({...}) 直接写，但绕过了 action 里的业务规则。
 */
function logoutAndClearCart() {
  useCartStore.getState().clear()
}

function LogPanel({ log }: { log: DemoLog }) {
  const lines = useSyncExternalStore(log.subscribe, log.getSnapshot)
  return (
    <pre className="log" aria-label="subscribe 日志">
      {lines.length === 0 ? '（还没有变化）' : lines.join('\n')}
    </pre>
  )
}

export function StoreApiDemo({ delayMs = 600 }: { delayMs?: number }) {
  const [log] = useState(createDemoLog)
  const [snapshotText, setSnapshotText] = useState('')
  const [storageText, setStorageText] = useState('')
  const [failNext, setFailNext] = useState(false)

  // 选一个对象没问题：checkout 只在 set 时被整体替换，没变时引用不变（Object.is 相同）
  const checkout = useCartStore((s) => s.checkout)
  const checkoutCart = useCartStore((s) => s.checkoutCart)

  /**
   * subscribe 在组件外也能用；在组件里用时放进 Effect，并把它返回的取消函数作为 cleanup。
   * 这里只写日志、不 setState，所以日志放在组件外的 log 里。
   * 需要「只在某个字段变化时回调」可以换 subscribeWithSelector 中间件，或者像这样自己比较 prev。
   */
  useEffect(
    () =>
      useCartStore.subscribe((state, prev) => {
        for (const line of describeChange(state, prev)) log.push(line)
      }),
    [log],
  )

  const readSnapshot = () => {
    // 事件处理函数里用 getState() 读最新值：不订阅，所以不会因为 store 变化而重渲染本组件
    const s = useCartStore.getState()
    setSnapshotText(`getState()：${selectTotalCount(s)} 件，礼品包装 ${s.giftWrap ? '是' : '否'}，结算状态 ${s.checkout.status}`)
  }

  const readStorage = () => {
    setStorageText(localStorage.getItem(CART_STORAGE_KEY) ?? '（localStorage 里没有这个键）')
  }

  const writeLegacyAndRehydrate = async () => {
    // 模拟「老版本代码写下的数据」：v0 的条目字段叫 qty。rehydrate 时版本号不一致 → 调 migrate → 写回 v1
    localStorage.setItem(
      CART_STORAGE_KEY,
      JSON.stringify({ state: { items: [{ id: 'p2', name: '无线鼠标', price: 149, qty: 3 }] }, version: 0 }),
    )
    await useCartStore.persist.rehydrate()
    readStorage()
  }

  const pending = checkout.status === 'pending'

  return (
    <div className="card stack">
      <h3>区块二：组件外读写、subscribe、异步 action、persist（主线）</h3>

      <strong>1. 组件外读写</strong>
      <div className="row">
        <button onClick={readSnapshot}>getState() 读一次（不订阅）</button>
        <button onClick={logoutAndClearCart}>模拟「退出登录」：非 React 代码清空购物车</button>
      </div>
      {snapshotText && <p className="muted">{snapshotText}</p>}

      <strong>2. 异步 action：结算</strong>
      <div className="row">
        <button className="btn-primary" disabled={pending} onClick={() => void checkoutCart({ delayMs, fail: failNext })}>
          {pending ? '结算中…' : '结算'}
        </button>
        <button
          disabled={pending}
          onClick={() => {
            // 同一轮里连调两次：第二次 get() 已经读到 'pending'，直接返回（set 是同步生效的）
            void checkoutCart({ delayMs, fail: failNext })
            void checkoutCart({ delayMs, fail: failNext })
          }}
        >
          同一轮里调用两次 checkoutCart()
        </button>
        <label className="row">
          <input type="checkbox" checked={failNext} onChange={(e) => setFailNext(e.target.checked)} />
          模拟结算失败
        </label>
      </div>
      <p role="status">
        结算状态：{checkout.status}
        {checkout.status === 'success' && `，订单号 ${checkout.orderNo}`}
      </p>
      {checkout.status === 'error' && (
        <p role="alert" className="error-text">
          {checkout.message}（购物车保留，可以重试）
        </p>
      )}

      <strong>3. persist：只持久化白名单字段</strong>
      <div className="row">
        <button onClick={readStorage}>查看 localStorage</button>
        <button
          onClick={() => {
            // 只删存储里的这一项；内存里的 store 不变，下一次 set 又会写回去
            useCartStore.persist.clearStorage()
            readStorage()
          }}
        >
          persist.clearStorage()
        </button>
        <button onClick={() => void writeLegacyAndRehydrate()}>写入 v0 旧数据 → rehydrate（触发 migrate）</button>
      </div>
      {storageText && (
        <pre className="log" aria-label="localStorage 内容">
          {storageText}
        </pre>
      )}

      <strong>4. subscribe 日志（组件外监听，Effect cleanup 里取消）</strong>
      <LogPanel log={log} />
    </div>
  )
}
