// src/topics/11-api-request-state/vue/Example.vue
<script setup lang="ts">
/**
 * 学习主题：API 请求状态建模 —— loading / success / error / empty 与重试
 *
 * React 核心概念：
 * - 工业界标准：用判别联合建模请求状态 status: 'loading' | 'success' | 'error'，
 *   data 只在 success 分支、errorMessage 只在 error 分支 —— 比多个独立 boolean 更不易出非法状态
 * - empty（请求成功但没数据）和 error（请求失败）是两种不同状态，UI 文案与交互都要分开
 * - 重试 = 让同一个请求 effect 重新执行：把 reloadFlag 计数器放进依赖数组，+1 即重跑
 * - 请求逻辑直接写在组件里，不做半吊子抽象；真实业务多用 TanStack Query，但手写这套是面试必备
 *
 * Vue 对应概念：
 * - 同样的判别联合放进 ref<RequestState>，整体替换 state.value —— 状态建模与 React 完全一致
 * - React 靠「改变依赖触发 effect 重跑」来重试；Vue 把请求写成普通函数 load()，重试直接再调一次
 *
 * 最重要的区别：
 * - 请求状态建模是框架无关的工程功底，两边一模一样；差异只在「怎么触发请求」：
 *   React 把请求声明成「状态的同步结果」（effect 由依赖驱动），
 *   Vue 版则把请求当成命令式「动作」（onMounted / 事件处理器里直接调 load）。
 */
import { onMounted, onUnmounted, ref } from 'vue'
import { fetchUsers, isAbortError } from '@/shared/mockApi'
import type { User } from '@/shared/types'

// 与 React 版逐字相同的判别联合 —— 两边的状态设计完全一致，差异只在响应式 API。
// 同样杜绝 isLoading && isError 之类的非法组合；模板里 v-if="state.status === 'success'"
// 收窄后，TS 同样能保证 state.users 存在。
// （React 侧的面试点这里同样成立；Vue 生态的现成方案是 @tanstack/vue-query，30 题会引入并对照。）
type RequestState =
  | { status: 'loading' }
  | { status: 'success'; users: User[] }
  | { status: 'error'; message: string }

const draft = ref('') // 输入框草稿
const keyword = ref('') // 已提交的搜索词（真正的请求参数）
// 「整体替换」的状态用 ref 而不是 reactive：reactive 不能整体换引用，
// state.value = { ... } 正好对应 React 的 setState(新对象)。
const state = ref<RequestState>({ status: 'loading' })

// React 版没有这个变量（controller 存在每轮 effect 的闭包里，cleanup 直接引用）；
// Vue 版的 load 是普通函数，需要自己记住「上一次」的 controller 用于取消。
let controller: AbortController | undefined

// React 版把请求声明成「由 [keyword, reloadFlag] 驱动的 effect」，初始加载/搜索/重试
// 都通过改依赖触发重跑；Vue 版直接写成普通函数，三个入口命令式地调它 ——
// 所以不需要 reloadFlag 这种「专门触发重跑的计数器」。请求逻辑同样直接写在组件里，不抽象。
async function load() {
  controller?.abort() // 取消上一次未完成的请求，避免竞态（10 题讲过；对应 React 的 cleanup）
  const ctrl = new AbortController()
  controller = ctrl
  state.value = { status: 'loading' }
  try {
    // failRate: 0.35 与 React 版一致 —— 35% 概率随机失败，方便看到 error 分支和重试按钮
    const users = await fetchUsers(keyword.value, { signal: ctrl.signal, failRate: 0.35 })
    state.value = { status: 'success', users }
  } catch (err) {
    if (isAbortError(err)) return // 「被取消」不算失败（10 题讲过）
    state.value = { status: 'error', message: err instanceof Error ? err.message : '未知错误' }
  }
}

// 初始自动加载：React 版靠「effect 挂载后必然执行一次」自动完成，Vue 版显式在 onMounted 调用
onMounted(load)
// React 版 effect cleanup 里的 abort 已覆盖卸载时机；Vue 版单独用 onUnmounted 取消在途请求
onUnmounted(() => controller?.abort())

// 提交搜索：React 版这里要 setKeyword + setReloadFlag(n => n + 1)（两次 setState 被批处理成
// 一次重渲染，再由 effect 重跑）；Vue 版赋值后直接调 load()，搜同一个词自然也会重新请求。
function handleSearch() {
  keyword.value = draft.value
  load()
}

// 重试：React 版靠 reloadFlag +1 触发 effect 重跑；Vue 版直接把同一个 load 再调一次
function retry() {
  load()
}
</script>

<template>
  <div class="stack">
    <p class="muted">
      初始自动加载用户列表；35% 概率随机失败，多点几次「重试」可看到 error 分支；搜「zzz」看空态
    </p>

    <!-- @submit.prevent 对应 React 的 e.preventDefault()；用 form 包裹是为了让回车也能触发搜索。
         加载中禁用输入与按钮：防止重复提交，请求结束（成功或失败）后自动恢复 -->
    <form
      class="row"
      @submit.prevent="handleSearch"
    >
      <input
        v-model="draft"
        placeholder="搜索姓名或邮箱，搜「zzz」看空态"
        :disabled="state.status === 'loading'"
      >
      <button
        type="submit"
        class="btn-primary"
        :disabled="state.status === 'loading'"
      >
        {{ state.status === 'loading' ? '加载中…' : '搜索' }}
      </button>
    </form>

    <!-- 四种 UI 形态一一对应四种状态（与 React 版逐一对应）。
         注意 empty 不是 error：它是「请求成功、数据恰好为空」，文案是引导换关键词而不是报错重试。 -->
    <p
      v-if="state.status === 'loading'"
      class="muted"
    >
      加载中，请稍候…
    </p>

    <div
      v-if="state.status === 'error'"
      class="card"
    >
      <!-- 收窄到 error 分支后，TS 保证 state.message 存在 -->
      <p class="error-text">
        {{ state.message }}
      </p>
      <!-- 重试按钮只出现在 error 分支；React 版点击后靠 reloadFlag 触发 effect 重跑 -->
      <button
        class="btn-primary"
        @click="retry"
      >
        重试
      </button>
    </div>

    <p
      v-if="state.status === 'success' && state.users.length === 0"
      class="muted"
    >
      没有找到{{ keyword ? `与「${keyword}」` : '' }}匹配的用户，换个关键词试试
    </p>

    <table v-if="state.status === 'success' && state.users.length > 0">
      <thead>
        <tr>
          <th>姓名</th>
          <th>邮箱</th>
          <th>角色</th>
        </tr>
      </thead>
      <tbody>
        <tr
          v-for="u in state.users"
          :key="u.id"
        >
          <td>{{ u.name }}</td>
          <td>{{ u.email }}</td>
          <td><span class="badge">{{ u.role }}</span></td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

// src/topics/11-api-request-state/react/Example.tsx
/**
 * 学习主题：API 请求状态建模 —— loading / success / error / empty 与重试
 *
 * React 核心概念：
 * - 工业界标准：用判别联合建模请求状态 status: 'loading' | 'success' | 'error'，
 *   data 只在 success 分支、errorMessage 只在 error 分支 —— 比多个独立 boolean 更不易出非法状态
 * - empty（请求成功但没数据）和 error（请求失败）是两种不同状态，UI 文案与交互都要分开
 * - 重试 = 让同一个请求 effect 重新执行：把 reloadFlag 计数器放进依赖数组，+1 即重跑
 * - 请求逻辑直接写在组件里，不做半吊子抽象；真实业务多用 TanStack Query，但手写这套是面试必备
 *
 * Vue 对应概念：
 * - 同样的判别联合放进 ref<RequestState>，整体替换 state.value —— 状态建模与 React 完全一致
 * - React 靠「改变依赖触发 effect 重跑」来重试；Vue 把请求写成普通函数 load()，重试直接再调一次
 *
 * 最重要的区别：
 * - 请求状态建模是框架无关的工程功底，两边一模一样；差异只在「怎么触发请求」：
 *   React 把请求声明成「状态的同步结果」（effect 由依赖驱动），
 *   Vue 版则把请求当成命令式「动作」（onMounted / 事件处理器里直接调 load）。
 */
import { useEffect, useState, type FormEvent } from 'react'
import { fetchUsers, isAbortError } from '@/shared/mockApi'
import type { User } from '@/shared/types'

/**
 * 工业界标准写法：判别联合（discriminated union）建模请求状态。
 * status 是判别字段；users 只在 success 分支存在，message 只在 error 分支存在。
 * TS 在 if (state.status === 'success') 收窄后能【保证】state.users 一定存在。
 *
 * 对比三个独立 boolean 的写法（isLoading + isError + data + errorMessage 各自为政）：
 * 那样可能出现 isLoading 和 isError 同时为 true、或「成功了 data 却是 null」的非法组合，
 * 每处 UI 都要靠人肉约定小心维护；判别联合让非法状态「根本无法被表示」—— 面试加分点。
 *
 * 真实业务通常直接用 TanStack Query：useQuery 内部就是这套状态机的完整体
 * （外加缓存/去重/自动重试/失效）。本课程不引入第三方库，但你要能手写出来。
 */
type RequestState =
  | { status: 'loading' }
  | { status: 'success'; users: User[] }
  | { status: 'error'; message: string }

export default function Example() {
  const [draft, setDraft] = useState('') // 输入框草稿
  const [keyword, setKeyword] = useState('') // 已提交的搜索词（真正的请求参数）
  const [reloadFlag, setReloadFlag] = useState(0) // 专门用来触发 effect 重跑的计数器
  const [state, setState] = useState<RequestState>({ status: 'loading' })

  /**
   * 请求 effect：依赖 [keyword, reloadFlag]，三个触发源统一成一条数据流 ——
   * - 挂载后自动执行一次 → 初始自动加载；
   * - 提交搜索改 keyword → 依赖变化，重新请求；
   * - 点「重试」把 reloadFlag +1 → 依赖变化，同一段请求逻辑原样重跑 —— 这就是重试的实现。
   *   （另一种做法是抽 load() 函数在各处手动调用；不引库时「依赖驱动 + reloadFlag」是常见手写模式。）
   *
   * 请求逻辑就这样直接写在组件里 —— 不急着抽 useFetch 之类的半吊子抽象；
   * 要抽象就上成熟的 TanStack Query。竞态处理与 10 题相同：cleanup 里 abort 旧请求。
   * failRate: 0.35 —— 35% 的请求随机失败，方便你亲眼看到 error 分支和重试按钮。
   */
  useEffect(() => {
    const controller = new AbortController()
    setState({ status: 'loading' })
    fetchUsers(keyword, { signal: controller.signal, failRate: 0.35 })
      .then((users) => setState({ status: 'success', users }))
      .catch((err: unknown) => {
        if (isAbortError(err)) return // 「被取消」不算失败（10 题讲过）
        setState({
          status: 'error',
          message: err instanceof Error ? err.message : '未知错误',
        })
      })
    return () => controller.abort()
  }, [keyword, reloadFlag])

  const loading = state.status === 'loading'

  /**
   * 提交搜索：keyword 换成草稿值，同时 reloadFlag +1 —— 这样搜索「同一个词」也会重新请求
   * （否则 setKeyword 传相同值，state 没变、effect 不会重跑）。
   * 同一事件里的两次 setState 会被 React 自动批处理成一次重渲染 → effect 只重跑一次。
   */
  const handleSearch = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault() // 阻止 form 默认的整页刷新；用 form 包裹是为了让回车也能触发搜索
    setKeyword(draft)
    setReloadFlag((n) => n + 1)
  }

  /** 重试：只改 reloadFlag，keyword 不动 —— 用同样的参数把失败的请求再发一次 */
  const retry = () => setReloadFlag((n) => n + 1)

  return (
    <div className="stack">
      <p className="muted">
        初始自动加载用户列表；35% 概率随机失败，多点几次「重试」可看到 error 分支；搜「zzz」看空态
      </p>

      <form className="row" onSubmit={handleSearch}>
        {/* 加载中禁用输入与按钮：防止重复提交，请求结束（成功或失败）后自动恢复 */}
        <input
          value={draft}
          onChange={(e) => setDraft(e.target.value)}
          placeholder="搜索姓名或邮箱，搜「zzz」看空态"
          disabled={loading}
        />
        <button type="submit" className="btn-primary" disabled={loading}>
          {loading ? '加载中…' : '搜索'}
        </button>
      </form>

      {/* 四种 UI 形态一一对应四种状态：loading / error / 空 success / 有数据 success。
          注意 empty 不是 error：它是「请求成功、数据恰好为空」，文案是引导换关键词而不是报错重试。 */}
      {state.status === 'loading' && <p className="muted">加载中，请稍候…</p>}

      {state.status === 'error' && (
        <div className="card">
          {/* 收窄到 error 分支后，TS 保证 state.message 存在 */}
          <p className="error-text">{state.message}</p>
          {/* 重试按钮只出现在 error 分支；点击后 effect 重跑，状态自然回到 loading */}
          <button className="btn-primary" onClick={retry}>
            重试
          </button>
        </div>
      )}

      {state.status === 'success' && state.users.length === 0 && (
        <p className="muted">没有找到{keyword ? `与「${keyword}」` : ''}匹配的用户，换个关键词试试</p>
      )}

      {state.status === 'success' && state.users.length > 0 && (
        <table>
          <thead>
            <tr>
              <th>姓名</th>
              <th>邮箱</th>
              <th>角色</th>
            </tr>
          </thead>
          <tbody>
            {state.users.map((u) => (
              <tr key={u.id}>
                <td>{u.name}</td>
                <td>{u.email}</td>
                <td>
                  <span className="badge">{u.role}</span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  )
}
