// src/topics/07-forms/react/ControlledProfileForm.tsx
/**
 * 【主线：受控】个人资料表单。每个字段的值都来自 state，每次输入都走一遍 onChange → setState → 重新渲染。
 *
 * 本文件演示：
 * - 一个对象 state + 按 name 分发的通用 handleChange + 函数式不可变更新（03 / 21 题）；
 * - 各种元素的受控写法：文本、type="number"、<select value>、<textarea value>、radio / checkbox 用 checked；
 * - 输入过滤：onChange 不把非法输入写进 state，事件结束后 React 把 DOM 改回 state（手机号只收数字）；
 * - 校验结果是派生值（09 题）：点过一次「保存」之后，错误信息随输入实时更新，不另存一份 state；
 * - 无障碍：TextField 用 useId 关联 label 和错误信息；提交失败时把焦点移到第一个出错的字段；
 * - 只读字段写 readOnly，不要只给 value 不给 onChange。
 *
 * Vue 对照：vue/ControlledProfileForm.vue（v-model 版，同样的字段和校验）。
 */
import { useRef, useState, type ChangeEvent, type SubmitEvent } from 'react'
import type { UserRole } from '@/shared/types'
import { TextField } from './TextField'

type ContactChannel = 'email' | 'phone'

/** 整个表单收进一个对象 —— 字段不多时最常见的组织方式 */
export interface ProfileForm {
  name: string
  /** 只存数字，最多 11 位 */
  phone: string
  /**
   * 年龄输入框是 type="number"，但 e.target.value 仍然是字符串。
   * 用字符串存才能表示「还没填」（空串）；提交时再 Number() 转换。
   * 浏览器对 "12." 这类半截输入的处理见 19 题。
   */
  age: string
  role: UserRole
  bio: string
  contact: ContactChannel
  subscribe: boolean
}

/** 保存下来的结果：年龄已经转成数字，没填是 null */
type SavedProfile = Omit<ProfileForm, 'age'> & { age: number | null }

type FieldErrors = Partial<Record<'name' | 'phone' | 'age', string>>

const ROLE_TEXT: Record<UserRole, string> = {
  admin: '管理员',
  editor: '编辑',
  viewer: '只读访客',
}
const ROLE_OPTIONS: UserRole[] = ['admin', 'editor', 'viewer']

const CONTACT_TEXT: Record<ContactChannel, string> = {
  email: '邮件',
  phone: '电话',
}
const CONTACT_OPTIONS: ContactChannel[] = ['email', 'phone']

/**
 * 受控字段的初始值都是确定的字符串 / 布尔值，不能是 undefined：
 * value 先是 undefined（React 当成非受控）后来变成字符串（变成受控），开发环境会报
 * 「A component is changing an uncontrolled input to be controlled」（Example.test.tsx 有断言）。
 */
const INITIAL_PROFILE: ProfileForm = {
  name: '林小满',
  phone: '',
  age: '',
  role: 'editor',
  bio: '',
  contact: 'email',
  subscribe: true,
}

/** 演示简化：手写 if 校验。生产里用 schema（如 zod）统一描述规则，而且后端要再校验一遍（35 题，待新增） */
function validateProfile(form: ProfileForm): FieldErrors {
  const errors: FieldErrors = {}
  if (form.name.trim() === '') errors.name = '姓名不能为空'
  if (form.contact === 'phone' && form.phone.length !== 11) errors.phone = '选择电话联系时，手机号要填满 11 位'
  if (form.age !== '') {
    const age = Number(form.age)
    if (!Number.isInteger(age) || age < 1 || age > 150) errors.age = '年龄要是 1–150 之间的整数'
  }
  return errors
}

export function ControlledProfileForm() {
  const [form, setForm] = useState<ProfileForm>(INITIAL_PROFILE)
  // 点过「保存」之后才开始显示错误
  const [submitted, setSubmitted] = useState(false)
  const [saved, setSaved] = useState<SavedProfile | null>(null)

  // 错误信息是派生值：每次渲染从 form 算出来，不用 useState 再存一份，也就不会和 form 对不上（09 题）
  const errors = submitted ? validateProfile(form) : {}

  // React 19：ref 作为普通 prop 传给 TextField，拿到的是它里面的 <input>（提交失败时聚焦用）
  const nameRef = useRef<HTMLInputElement>(null)
  const phoneRef = useRef<HTMLInputElement>(null)
  const ageRef = useRef<HTMLInputElement>(null)

  /**
   * 通用 handleChange：所有字段共用一个处理函数，靠 name 属性决定更新哪个字段。
   * Vue 里这个函数不需要存在：v-model 直接绑到 form.xxx。
   */
  function handleChange(e: ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) {
    const { name, value } = e.target
    // checkbox 的值在 checked 上，不在 value 上；radio 的 value 就是选项自己的值，照常读 value
    const nextValue = e.target instanceof HTMLInputElement && e.target.type === 'checkbox' ? e.target.checked : value
    // 展开旧对象 + 计算属性名 [name] 覆盖一个字段（不可变更新，03 / 21 题）。
    // 代价：TS 检查不出 name 字符串和字段类型是否匹配，name 必须和 ProfileForm 的键一致。
    setForm((prev) => ({ ...prev, [name]: nextValue }))
  }

  /**
   * 输入过滤：非法输入直接不写进 state。
   * 这时 state 没变，但 DOM 里已经多了一个字母 —— React 在这次事件处理结束后，会把输入框的值改回 props 里的 value
   * （react-dom 19.2.8 的 batchedUpdates 结束时调用 restoreStateOfTarget），用户看到的就是「字母被弹回去了」。
   * 这正是「受控」的含义：「React will force the input to always have the value you passed」。
   * Vue 的 v-model 不会这样做，写法差异见 vue/InputEventLab.vue。
   *
   * 两个限制（官方 Troubleshooting「My input caret jumps to the beginning on every keystroke」）：
   * - 接受的输入要同步地原样写进 state（e.target.value）。放进 setTimeout / await 之后再 set，
   *   或者写成别的值（例如 toUpperCase()），光标会乱跳；
   * - 被弹回时 React 重新设置了 value，光标会跳到末尾（2026-09-17 在 Chrome 实测：在「1380」的第 1 位后敲字母，
   *   值还是 1380，光标到了最后；敲数字则光标正常停在插入处）。所以生产里的金额、分段手机号这类格式化输入，
   *   通常交给输入掩码组件，或者只在失焦 / 提交时格式化。
   */
  function handlePhoneChange(e: ChangeEvent<HTMLInputElement>) {
    const { value } = e.target
    if (!/^\d{0,11}$/.test(value)) return
    setForm((prev) => ({ ...prev, phone: value }))
  }

  /**
   * onSubmit 挂在 <form> 上，而不是按钮的 onClick：在输入框里按回车、点 type="submit" 的按钮都会触发。
   * 必须 e.preventDefault()，否则浏览器按传统方式提交表单并刷新页面。Vue 写 @submit.prevent。
   * 事件类型用 SubmitEvent<HTMLFormElement>：@types/react 19.2 已把 FormEvent 标成 @deprecated（28 题）。
   */
  function handleSubmit(e: SubmitEvent<HTMLFormElement>) {
    e.preventDefault()
    setSubmitted(true)
    const nextErrors = validateProfile(form)
    // 焦点移到第一个出错的字段（顺序和页面一致），键盘和读屏用户能直接看到出了什么错
    const firstInvalid = nextErrors.name ? nameRef : nextErrors.phone ? phoneRef : nextErrors.age ? ageRef : null
    if (firstInvalid) {
      firstInvalid.current?.focus()
      setSaved(null)
      return
    }
    // 提交中的 loading、防重复、接口失败提示在 19 题；React 19 的 <form action> 写法在 31 题（待新增）
    setSaved({ ...form, name: form.name.trim(), age: form.age === '' ? null : Number(form.age) })
  }

  function handleReset() {
    setForm(INITIAL_PROFILE)
    setSubmitted(false)
    setSaved(null)
  }

  return (
    <div className="card stack">
      <h3>区块一：受控表单【主线】—— 个人资料</h3>
      <p className="muted">
        每个输入框的值都来自 state。每输入一个字符：onChange → setForm → 组件重新渲染 → 新的 value 写回输入框。
      </p>

      {/* noValidate：校验和错误提示由我们自己做，关掉浏览器自带的校验气泡，免得两套提示打架 */}
      <form className="stack" noValidate onSubmit={handleSubmit}>
        <TextField ref={nameRef} label="姓名" name="name" value={form.name} onChange={handleChange} error={errors.name} />

        <TextField
          ref={phoneRef}
          label="手机号"
          name="phone"
          value={form.phone}
          onChange={handlePhoneChange}
          inputMode="numeric"
          hint="只收数字，最多 11 位。敲个字母试试：字母会被弹回去"
          error={errors.phone}
        />

        <TextField
          ref={ageRef}
          label="年龄"
          name="age"
          type="number"
          value={form.age}
          onChange={handleChange}
          hint={'选填。type="number" 的 value 也是字符串，提交时再转成数字'}
          error={errors.age}
        />

        <label className="row">
          角色
          {/* <select value> 受控：选中项由 <select> 的 value 决定。
              React 不支持给 <option> 写 selected（官方：「passing a selected attribute to <option> is not supported」）；
              多选时写 multiple，value 是字符串数组。Vue 同样是 v-model 绑在 <select> 上。 */}
          <select name="role" value={form.role} onChange={handleChange}>
            {ROLE_OPTIONS.map((role) => (
              <option key={role} value={role}>
                {ROLE_TEXT[role]}
              </option>
            ))}
          </select>
        </label>

        <label className="stack" style={{ gap: 4 }}>
          简介
          {/* <textarea value> 受控；React 不支持把初始文字写成 <textarea>children</textarea>，
              受控用 value，非受控用 defaultValue */}
          <textarea name="bio" rows={2} value={form.bio} onChange={handleChange} placeholder="选填" />
        </label>

        {/* 一组 radio：fieldset + legend 给这组选项一个名字（读屏软件会读出「联系方式」）。
            每个 radio 用 checked={当前值 === 选项值}，同一个 name 让浏览器知道它们是一组 */}
        <fieldset style={{ border: 'none', padding: 0, margin: 0 }}>
          <legend style={{ padding: 0 }}>联系方式</legend>
          <div className="row">
            {CONTACT_OPTIONS.map((channel) => (
              <label key={channel} className="row" style={{ gap: 4 }}>
                <input
                  type="radio"
                  name="contact"
                  value={channel}
                  checked={form.contact === channel}
                  onChange={handleChange}
                />
                {CONTACT_TEXT[channel]}
              </label>
            ))}
          </div>
        </fieldset>

        <label className="row">
          {/* checkbox 受控用 checked，不是 value；读值用 e.target.checked */}
          <input type="checkbox" name="subscribe" checked={form.subscribe} onChange={handleChange} />
          订阅通知
        </label>

        <label className="row">
          账号 ID
          {/* 只给 value 不给 onChange，开发环境会报「You provided a `value` prop to a form field without an
              `onChange` handler」，而且输入框打不进字。本来就要只读时，显式写 readOnly，报错随之消失。 */}
          <input value="U-2026-0007" readOnly />
        </label>

        <div className="row">
          <button type="submit" className="btn-primary">
            保存
          </button>
          {/* <form> 里的 <button> 默认 type="submit"，普通按钮必须写 type="button"，否则点了会提交表单 */}
          <button type="button" onClick={handleReset}>
            重置
          </button>
        </div>
      </form>

      {/* 受控的直接好处：state 随输入实时更新，渲染里随时能用它（联动、实时校验、按内容禁用按钮） */}
      <p className="muted">
        实时 state：<code style={{ wordBreak: 'break-all' }}>{JSON.stringify(form)}</code>
      </p>

      {saved !== null && (
        <div className="stack" style={{ gap: 4 }}>
          <p className="success-text" style={{ margin: 0 }}>
            保存成功（演示：只存在本地 state）
          </p>
          <p style={{ margin: 0 }}>
            {saved.name} · {ROLE_TEXT[saved.role]} · 年龄 {saved.age ?? '未填'} · {CONTACT_TEXT[saved.contact]}联系 ·
            {saved.subscribe ? ' 已订阅' : ' 未订阅'}
          </p>
        </div>
      )}
    </div>
  )
}

// src/topics/07-forms/vue/ControlledProfileForm.vue
<script setup lang="ts">
/**
 * 【主线：受控】个人资料表单（React 对照：react/ControlledProfileForm.tsx，字段和校验一致）。
 *
 * v-model 就是 Vue 里的受控写法：输入框显示什么由 form 决定，官方原文
 * 「v-model will ignore the initial value, checked or selected attributes ... treat the current bound JavaScript state
 * as the source of truth」。和 React 的差别：
 * - 不用写 value + onChange + name 分发，v-model 按元素类型自动选属性和事件；
 * - type="number" 的 v-model 自动带 .number：能解析成数字就存 number，清空时是 ''（React 侧 state 存字符串）；
 * - 输入过滤：v-model 不会把被拒绝的输入从 DOM 里改回去，所以手机号改用 :value + @input 手动改回；
 * - 错误信息同样是派生值（computed），聚焦第一个出错字段用 useTemplateRef + TextField 暴露的 focus()。
 */
import { computed, reactive, ref, useId, useTemplateRef } from 'vue'
import type { UserRole } from '@/shared/types'
import TextField from './TextField.vue'

type ContactChannel = 'email' | 'phone'

interface ProfileForm {
  name: string
  phone: string
  /** v-model + type="number"：解析得了是 number，清空时是空串（官方：if the input is empty ... an empty string is returned） */
  age: number | ''
  role: UserRole
  bio: string
  contact: ContactChannel
  subscribe: boolean
}

type FieldErrors = Partial<Record<'name' | 'phone' | 'age', string>>

const ROLE_TEXT: Record<UserRole, string> = {
  admin: '管理员',
  editor: '编辑',
  viewer: '只读访客',
}
const ROLE_OPTIONS: UserRole[] = ['admin', 'editor', 'viewer']
const CONTACT_TEXT: Record<ContactChannel, string> = { email: '邮件', phone: '电话' }
const CONTACT_OPTIONS: ContactChannel[] = ['email', 'phone']

const INITIAL_PROFILE: ProfileForm = {
  name: '林小满',
  phone: '',
  age: '',
  role: 'editor',
  bio: '',
  contact: 'email',
  subscribe: true,
}

// React 版是 useState<ProfileForm>(INITIAL_PROFILE)；Vue 用 reactive 包一个副本，v-model 直接改它的属性
const form = reactive<ProfileForm>({ ...INITIAL_PROFILE })
const submitted = ref(false)
const saved = ref<ProfileForm | null>(null)

/** 演示简化：手写校验（与 React 侧相同），生产用 schema 校验，后端再校验一遍 */
function validateProfile(value: ProfileForm): FieldErrors {
  const errors: FieldErrors = {}
  if (value.name.trim() === '') errors.name = '姓名不能为空'
  if (value.contact === 'phone' && value.phone.length !== 11) errors.phone = '选择电话联系时，手机号要填满 11 位'
  if (value.age !== '' && (!Number.isInteger(value.age) || value.age < 1 || value.age > 150)) {
    errors.age = '年龄要是 1–150 之间的整数'
  }
  return errors
}

// 派生值：React 侧在渲染里直接算，Vue 用 computed（带缓存）
const errors = computed<FieldErrors>(() => (submitted.value ? validateProfile(form) : {}))

// 手机号、年龄没有用 TextField，自己调 useId；同一个组件调用两次得到两个不同的 id
const phoneId = useId()
const ageId = useId()

const nameField = useTemplateRef<InstanceType<typeof TextField>>('nameField')
const phoneInput = useTemplateRef<HTMLInputElement>('phoneInput')
const ageInput = useTemplateRef<HTMLInputElement>('ageInput')

/**
 * 输入过滤的 Vue 写法。不能直接用 v-model：非法输入不写进 form 时，form 没变、组件不重新渲染，
 * v-model 也就不会把 DOM 改回去（它只在 beforeUpdate 里写回），字母会留在输入框里。
 * 所以拒绝时手动把 el.value 改回 form.phone。React 的受控输入在事件结束后自动改回。
 */
function onPhoneInput(e: Event) {
  const el = e.target as HTMLInputElement
  if (/^\d{0,11}$/.test(el.value)) {
    form.phone = el.value
  } else {
    el.value = form.phone
  }
}

// React 要手动 e.preventDefault()；模板上的 @submit.prevent 已经做了
function handleSubmit() {
  submitted.value = true
  const nextErrors = validateProfile(form)
  if (nextErrors.name) nameField.value?.focus()
  else if (nextErrors.phone) phoneInput.value?.focus()
  else if (nextErrors.age) ageInput.value?.focus()
  if (Object.keys(nextErrors).length > 0) {
    saved.value = null
    return
  }
  // 展开 reactive 得到一份普通对象快照
  saved.value = { ...form, name: form.name.trim() }
}

function handleReset() {
  Object.assign(form, INITIAL_PROFILE)
  submitted.value = false
  saved.value = null
}
</script>

<template>
  <div class="card stack">
    <h3>区块一：受控表单【主线】—— 个人资料</h3>
    <p class="muted">
      v-model 就是 Vue 的受控写法：输入框显示什么由 form 决定，输入时 v-model 把新值写回 form。
    </p>

    <!-- @submit.prevent：修饰符阻止默认提交；noValidate 关掉浏览器自带的校验气泡，和 React 侧一样 -->
    <form
      class="stack"
      novalidate
      @submit.prevent="handleSubmit"
    >
      <!-- 组件 v-model：TextField 里用 defineModel() 接住。ref="nameField" 拿到的是组件实例 -->
      <TextField
        ref="nameField"
        v-model="form.name"
        label="姓名"
        name="name"
        :error="errors.name"
      />

      <div
        class="stack"
        style="gap: 4px"
      >
        <div class="row">
          <label :for="phoneId">手机号</label>
          <input
            :id="phoneId"
            ref="phoneInput"
            name="phone"
            inputmode="numeric"
            :value="form.phone"
            :aria-invalid="errors.phone ? true : undefined"
            :aria-describedby="`${phoneId}-hint` + (errors.phone ? ` ${phoneId}-error` : '')"
            @input="onPhoneInput"
          >
        </div>
        <p
          :id="`${phoneId}-hint`"
          class="muted"
          style="margin: 0"
        >
          只收数字，最多 11 位。这里用 :value + @input 手动改回，敲字母同样会被弹回
        </p>
        <p
          v-if="errors.phone"
          :id="`${phoneId}-error`"
          class="error-text"
          style="margin: 0"
        >
          {{ errors.phone }}
        </p>
      </div>

      <div
        class="stack"
        style="gap: 4px"
      >
        <div class="row">
          <label :for="ageId">年龄</label>
          <!-- type="number" 的 v-model 自动加 .number 修饰符 -->
          <input
            :id="ageId"
            ref="ageInput"
            v-model="form.age"
            name="age"
            type="number"
            :aria-invalid="errors.age ? true : undefined"
            :aria-describedby="errors.age ? `${ageId}-error` : undefined"
          >
        </div>
        <p
          v-if="errors.age"
          :id="`${ageId}-error`"
          class="error-text"
          style="margin: 0"
        >
          {{ errors.age }}
        </p>
      </div>

      <label class="row">
        角色
        <!-- select 也是 v-model（value + change）。Vue 模板里写 <option selected> 不报错，但 v-model 会忽略它 -->
        <select
          v-model="form.role"
          name="role"
        >
          <option
            v-for="role in ROLE_OPTIONS"
            :key="role"
            :value="role"
          >
            {{ ROLE_TEXT[role] }}
          </option>
        </select>
      </label>

      <label
        class="stack"
        style="gap: 4px"
      >
        简介
        <!-- .trim 修饰符：写回 form 之前先去掉首尾空格（React 没有修饰符，要在 onChange 或提交时自己 trim） -->
        <textarea
          v-model.trim="form.bio"
          name="bio"
          rows="2"
          placeholder="选填"
        />
      </label>

      <fieldset style="border: none; padding: 0; margin: 0">
        <legend style="padding: 0">
          联系方式
        </legend>
        <div class="row">
          <label
            v-for="channel in CONTACT_OPTIONS"
            :key="channel"
            class="row"
            style="gap: 4px"
          >
            <!-- radio 的 v-model 是 checked + change；React 写 checked={form.contact === channel} -->
            <input
              v-model="form.contact"
              type="radio"
              name="contact"
              :value="channel"
            >
            {{ CONTACT_TEXT[channel] }}
          </label>
        </div>
      </fieldset>

      <label class="row">
        <input
          v-model="form.subscribe"
          type="checkbox"
          name="subscribe"
        >
        订阅通知
      </label>

      <label class="row">
        账号 ID
        <!-- Vue 里只写 value 不写事件不会报错；本来就只读，同样显式写 readonly -->
        <input
          value="U-2026-0007"
          readonly
        >
      </label>

      <div class="row">
        <button
          type="submit"
          class="btn-primary"
        >
          保存
        </button>
        <button
          type="button"
          @click="handleReset"
        >
          重置
        </button>
      </div>
    </form>

    <p class="muted">
      实时 state：<code style="word-break: break-all">{{ JSON.stringify(form) }}</code>
    </p>

    <div
      v-if="saved !== null"
      class="stack"
      style="gap: 4px"
    >
      <p
        class="success-text"
        style="margin: 0"
      >
        保存成功（演示：只存在本地 state）
      </p>
      <p style="margin: 0">
        {{ saved.name }} · {{ ROLE_TEXT[saved.role] }} · 年龄 {{ saved.age === '' ? '未填' : saved.age }} ·
        {{ CONTACT_TEXT[saved.contact] }}联系 · {{ saved.subscribe ? '已订阅' : '未订阅' }}
      </p>
    </div>
  </div>
</template>
