// src/topics/03-state/react/StateStructureDemo.tsx
/**
 * 区块五：state 的结构 —— 别存重复的数据（存 id，不存对象副本）、别让几个 state 互相矛盾（多个布尔值 → 一个 status）。
 * react.dev choosing-the-state-structure 五条原则里最常踩的两条（Avoid duplication、Avoid contradictions）；另外三条（Group related state、Avoid redundant state、
 * Avoid deeply nested state）见 Example.tsx 二-10。
 * Vue 对照：vue/StateStructureDemo.vue（Vue 里存同一个响应式对象，原地修改时不会过期，列表整体换新时同样过期，所以照样推荐存 id）。
 */
import { useState } from 'react'

interface Product {
  id: string
  name: string
  quantity: number
}

const PRODUCTS: Product[] = [
  { id: 'p1', name: '机械键盘', quantity: 1 },
  { id: 'p2', name: '无线鼠标', quantity: 2 },
]

/**
 * 同一份「选中了哪件商品」，两种存法：
 * - ❌ selectedItem：把对象本身存进另一个 state。items 更新时造的是新对象，selectedItem 还指着旧的那个 —— 详情停在选中那一刻；
 * - ✅ selectedId：只存 id，详情在渲染时从 items 里找（派生）。数据只有一份，只要 id 稳定，改了哪里都对得上（选中项被删掉时查到 null，显示未选中）。
 * react.dev：「the contents of the selectedItem is the same object as one of the items inside the items list. This means that the information about the item itself
 * is duplicated in two places.」（出自 choosing-the-state-structure 的 Avoid duplication in state 一节；结论见 Example.tsx 二-10）
 */
function SelectionDemo() {
  const [items, setItems] = useState(PRODUCTS)
  const [selectedItem, setSelectedItem] = useState<Product | null>(null)
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const selected = items.find((item) => item.id === selectedId) ?? null

  function select(item: Product) {
    setSelectedItem(item)
    setSelectedId(item.id)
  }

  function addOne(id: string) {
    setItems((prev) => prev.map((item) => (item.id === id ? { ...item, quantity: item.quantity + 1 } : item)))
  }

  return (
    <div className="stack">
      <h4>1）别存重复的数据：存 id，不存对象</h4>
      {items.map((item) => (
        <div key={item.id} className="row">
          <span>
            {item.name} × {item.quantity}
          </span>
          <button onClick={() => select(item)}>选中</button>
          <button onClick={() => addOne(item.id)}>+1</button>
        </div>
      ))}
      <ul className="stack">
        <li data-testid="selected-by-object">
          ❌ 存对象 selectedItem：{selectedItem ? `${selectedItem.name} × ${selectedItem.quantity}` : '（未选中）'}
        </li>
        <li data-testid="selected-by-id">✅ 存 id、渲染时查找：{selected ? `${selected.name} × ${selected.quantity}` : '（未选中）'}</li>
      </ul>
    </div>
  )
}

/**
 * ❌ 两个布尔值描述一件事：isSending 和 isSent 本不该同时为 true，但结构上允许，只要某处忘了同步改另一个，界面就出现「不可能的状态」。
 * 这里的 bug 很典型：再次发送时只设了 isSending = true，忘了把 isSent 改回 false。
 */
function SendWithBooleans() {
  const [isSending, setIsSending] = useState(false)
  const [isSent, setIsSent] = useState(false)

  function send() {
    setIsSending(true) // 忘了 setIsSent(false)
  }

  function serverReplied() {
    setIsSending(false)
    setIsSent(true)
  }

  return (
    <div className="row" data-testid="send-booleans">
      <strong>❌ 两个布尔值</strong>
      <button onClick={send}>发送</button>
      <button disabled={!isSending} onClick={serverReplied}>
        模拟服务器返回
      </button>
      {isSending && <span>发送中…</span>}
      {isSent && <span className="success-text">已发送 ✓</span>}
    </div>
  )
}

/**
 * ✅ 一个 status：取值只有三种合法组合，「发送中且已发送」在类型上就写不出来。
 * 需要布尔值时从 status 派生（const isSending = status === 'sending'），不另外存。
 * 这种字面量联合在 TypeScript 里要显式写泛型：useState<SendStatus>('typing')，否则会被推断成 string。
 */
type SendStatus = 'typing' | 'sending' | 'sent'

function SendWithStatus() {
  const [status, setStatus] = useState<SendStatus>('typing')
  const isSending = status === 'sending'
  const isSent = status === 'sent'

  return (
    <div className="row" data-testid="send-status">
      <strong>✅ 一个 status</strong>
      <button onClick={() => setStatus('sending')}>发送</button>
      <button disabled={!isSending} onClick={() => setStatus('sent')}>
        模拟服务器返回
      </button>
      {isSending && <span>发送中…</span>}
      {isSent && <span className="success-text">已发送 ✓</span>}
    </div>
  )
}

export function StateStructureDemo() {
  return (
    <div className="card stack">
      <h3>区块五：state 的结构 —— 别重复、别矛盾</h3>
      <SelectionDemo />
      <div className="stack">
        <h4>2）别让几个 state 互相矛盾：多个布尔值 → 一个 status</h4>
        <p className="muted">两边都按「发送 → 模拟服务器返回 → 发送」点一遍。</p>
        <SendWithBooleans />
        <SendWithStatus />
      </div>
    </div>
  )
}

// src/topics/03-state/vue/StateStructureDemo.vue
<script setup lang="ts">
/**
 * 区块五：state 的结构。对照 react/StateStructureDemo.tsx。
 *
 * 1）存对象还是存 id —— Vue 这边的表现和 React 不一样：
 * - 存同一个响应式对象（selectedItem.value = item）：原地修改时改的是同一个对象，详情跟着变，不会像 React 那样过期；
 * - 存一份副本（{ ...item }）：和 React 的问题一样，详情停在选中那一刻；
 * - 但只要列表被整体换成新对象（最常见的是重新请求接口），存下来的旧对象就和列表脱节了（点「重新拉取」试试）；
 *   存 id、渲染时用 computed 查找：只要 id 稳定，原地修改和整体换新都对得上（选中项被删掉时查到 null，显示未选中）—— 所以 Vue 里同样推荐存 id（测试覆盖三种存法）。
 * 2）多个布尔值 → 一个 status：这是建模原则，和框架无关。Vue 里一样用字面量联合的 ref，需要布尔值时用 computed 派生
 *   （React 侧演示了两个布尔值出现「发送中且已发送」的 bug，Vue 写两个 ref 布尔值会有同样的问题）。
 */
import { computed, ref } from 'vue'

interface Product {
  id: string
  name: string
  quantity: number
}

const PRODUCTS: Product[] = [
  { id: 'p1', name: '机械键盘', quantity: 1 },
  { id: 'p2', name: '无线鼠标', quantity: 2 },
]

const items = ref<Product[]>(PRODUCTS.map((p) => ({ ...p })))
const selectedItem = ref<Product | null>(null)
const selectedCopy = ref<Product | null>(null)
const selectedId = ref<string | null>(null)
const selected = computed(() => items.value.find((item) => item.id === selectedId.value) ?? null)

function select(item: Product) {
  selectedItem.value = item
  selectedCopy.value = { ...item }
  selectedId.value = item.id
}

function addOne(item: Product) {
  item.quantity += 1
}

// 模拟重新请求接口：数据还是那些，但每一项都是新对象（数量顺便 +10，好看出区别）
function refetch() {
  items.value = items.value.map((item) => ({ ...item, quantity: item.quantity + 10 }))
}

const show = (item: Product | null) => (item ? `${item.name} × ${item.quantity}` : '（未选中）')

type SendStatus = 'typing' | 'sending' | 'sent'
const status = ref<SendStatus>('typing')
const isSending = computed(() => status.value === 'sending')
const isSent = computed(() => status.value === 'sent')
</script>

<template>
  <div class="card stack">
    <h3>区块五：state 的结构 —— 别重复、别矛盾</h3>
    <div class="stack">
      <h4>1）别存重复的数据：存 id，不存对象</h4>
      <div
        v-for="item in items"
        :key="item.id"
        class="row"
      >
        <span>{{ item.name }} × {{ item.quantity }}</span>
        <button @click="select(item)">
          选中
        </button>
        <button @click="addOne(item)">
          +1
        </button>
      </div>
      <div class="row">
        <button @click="refetch">
          重新拉取（列表换成新对象）
        </button>
      </div>
      <ul class="stack">
        <li data-testid="selected-by-object">
          存同一个响应式对象：{{ show(selectedItem) }}
        </li>
        <li data-testid="selected-by-copy">
          ❌ 存副本：{{ show(selectedCopy) }}
        </li>
        <li data-testid="selected-by-id">
          ✅ 存 id、computed 查找：{{ show(selected) }}
        </li>
      </ul>
    </div>
    <div class="stack">
      <h4>2）多个布尔值 → 一个 status</h4>
      <div
        class="row"
        data-testid="send-status"
      >
        <strong>✅ 一个 status</strong>
        <button @click="status = 'sending'">
          发送
        </button>
        <button
          :disabled="!isSending"
          @click="status = 'sent'"
        >
          模拟服务器返回
        </button>
        <span v-if="isSending">发送中…</span>
        <span
          v-if="isSent"
          class="success-text"
        >已发送 ✓</span>
      </div>
    </div>
  </div>
</template>
